# 保密观自动化配置文件

# 课程 ID
course_packet_id: "312bc914-8e11-421b-b9bc-e900fe1a4e50"

# 多账号配置
accounts:
  - loginName: "151xxxxxxxx"
    passWord: "xxxx"
    token: ''
    timestamp: 0
    label: "示例账号"
    nickName: "张三"
